FROM node:22-alpine

#creates the working directory for consumer 
WORKDIR /app

#copy the package.json file to docker package.json 
COPY package*.json ./

RUN npm install --production

COPY . .

RUN mkdir -p logs

CMD [ "node","src/services/processor/consumer.js" ]